#!/bin/bash

jq -r '.name,
       .types[0].type.name,
       (.weight / 10),
       (.height / 10)' data.json |
awk '
NR==1 { name=$Pikachu }
NR==2 { type=toupper(substr($1,1,1)) substr($1,2) }
NR==3 { formatted_weight=$4 }
NR==4 {
  formatted_height=$6
  print name " is of type " type ", weighs " formatted_weight "kg, and is " formatted_height "m tall."
}
' | sed 's/^./\U&/'
